// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatData.proto

package protocol.Data;

public final class ChatData {
  private ChatData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChatItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string sendUserId = 1;
    /**
     * <code>required string sendUserId = 1;</code>
     */
    boolean hasSendUserId();
    /**
     * <code>required string sendUserId = 1;</code>
     */
    java.lang.String getSendUserId();
    /**
     * <code>required string sendUserId = 1;</code>
     */
    com.google.protobuf.ByteString
        getSendUserIdBytes();

    // required string receiveUserId = 2;
    /**
     * <code>required string receiveUserId = 2;</code>
     */
    boolean hasReceiveUserId();
    /**
     * <code>required string receiveUserId = 2;</code>
     */
    java.lang.String getReceiveUserId();
    /**
     * <code>required string receiveUserId = 2;</code>
     */
    com.google.protobuf.ByteString
        getReceiveUserIdBytes();

    // required .protocol.ChatItem.ChatType chatType = 3;
    /**
     * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
     */
    boolean hasChatType();
    /**
     * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
     */
    protocol.Data.ChatData.ChatItem.ChatType getChatType();

    // required string chatBody = 4;
    /**
     * <code>required string chatBody = 4;</code>
     */
    boolean hasChatBody();
    /**
     * <code>required string chatBody = 4;</code>
     */
    java.lang.String getChatBody();
    /**
     * <code>required string chatBody = 4;</code>
     */
    com.google.protobuf.ByteString
        getChatBodyBytes();
  }
  /**
   * Protobuf type {@code protocol.ChatItem}
   */
  public static final class ChatItem extends
      com.google.protobuf.GeneratedMessage
      implements ChatItemOrBuilder {
    // Use ChatItem.newBuilder() to construct.
    private ChatItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChatItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChatItem defaultInstance;
    public static ChatItem getDefaultInstance() {
      return defaultInstance;
    }

    public ChatItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChatItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sendUserId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              receiveUserId_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              protocol.Data.ChatData.ChatItem.ChatType value = protocol.Data.ChatData.ChatItem.ChatType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                chatType_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              chatBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Data.ChatData.internal_static_protocol_ChatItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Data.ChatData.internal_static_protocol_ChatItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Data.ChatData.ChatItem.class, protocol.Data.ChatData.ChatItem.Builder.class);
    }

    public static com.google.protobuf.Parser<ChatItem> PARSER =
        new com.google.protobuf.AbstractParser<ChatItem>() {
      public ChatItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChatItem> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.ChatItem.ChatType}
     */
    public enum ChatType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEXT = 0;</code>
       */
      TEXT(0, 0),
      /**
       * <code>IMAGE = 1;</code>
       */
      IMAGE(1, 1),
      ;

      /**
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <code>IMAGE = 1;</code>
       */
      public static final int IMAGE_VALUE = 1;


      public final int getNumber() { return value; }

      public static ChatType valueOf(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return IMAGE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ChatType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
              public ChatType findValueByNumber(int number) {
                return ChatType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Data.ChatData.ChatItem.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChatType[] VALUES = values();

      public static ChatType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ChatType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ChatItem.ChatType)
    }

    private int bitField0_;
    // required string sendUserId = 1;
    public static final int SENDUSERID_FIELD_NUMBER = 1;
    private java.lang.Object sendUserId_;
    /**
     * <code>required string sendUserId = 1;</code>
     */
    public boolean hasSendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sendUserId = 1;</code>
     */
    public java.lang.String getSendUserId() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sendUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sendUserId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSendUserIdBytes() {
      java.lang.Object ref = sendUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sendUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string receiveUserId = 2;
    public static final int RECEIVEUSERID_FIELD_NUMBER = 2;
    private java.lang.Object receiveUserId_;
    /**
     * <code>required string receiveUserId = 2;</code>
     */
    public boolean hasReceiveUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string receiveUserId = 2;</code>
     */
    public java.lang.String getReceiveUserId() {
      java.lang.Object ref = receiveUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          receiveUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string receiveUserId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getReceiveUserIdBytes() {
      java.lang.Object ref = receiveUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiveUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .protocol.ChatItem.ChatType chatType = 3;
    public static final int CHATTYPE_FIELD_NUMBER = 3;
    private protocol.Data.ChatData.ChatItem.ChatType chatType_;
    /**
     * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
     */
    public boolean hasChatType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
     */
    public protocol.Data.ChatData.ChatItem.ChatType getChatType() {
      return chatType_;
    }

    // required string chatBody = 4;
    public static final int CHATBODY_FIELD_NUMBER = 4;
    private java.lang.Object chatBody_;
    /**
     * <code>required string chatBody = 4;</code>
     */
    public boolean hasChatBody() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string chatBody = 4;</code>
     */
    public java.lang.String getChatBody() {
      java.lang.Object ref = chatBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chatBody_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string chatBody = 4;</code>
     */
    public com.google.protobuf.ByteString
        getChatBodyBytes() {
      java.lang.Object ref = chatBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      sendUserId_ = "";
      receiveUserId_ = "";
      chatType_ = protocol.Data.ChatData.ChatItem.ChatType.TEXT;
      chatBody_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReceiveUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChatBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSendUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getReceiveUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, chatType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getChatBodyBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSendUserIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getReceiveUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, chatType_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getChatBodyBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Data.ChatData.ChatItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Data.ChatData.ChatItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Data.ChatData.ChatItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Data.ChatData.ChatItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Data.ChatData.ChatItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ChatItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Data.ChatData.ChatItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Data.ChatData.internal_static_protocol_ChatItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Data.ChatData.internal_static_protocol_ChatItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Data.ChatData.ChatItem.class, protocol.Data.ChatData.ChatItem.Builder.class);
      }

      // Construct using protocol.Data.ChatData.ChatItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sendUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        receiveUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        chatType_ = protocol.Data.ChatData.ChatItem.ChatType.TEXT;
        bitField0_ = (bitField0_ & ~0x00000004);
        chatBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Data.ChatData.internal_static_protocol_ChatItem_descriptor;
      }

      public protocol.Data.ChatData.ChatItem getDefaultInstanceForType() {
        return protocol.Data.ChatData.ChatItem.getDefaultInstance();
      }

      public protocol.Data.ChatData.ChatItem build() {
        protocol.Data.ChatData.ChatItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Data.ChatData.ChatItem buildPartial() {
        protocol.Data.ChatData.ChatItem result = new protocol.Data.ChatData.ChatItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sendUserId_ = sendUserId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.receiveUserId_ = receiveUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.chatType_ = chatType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.chatBody_ = chatBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Data.ChatData.ChatItem) {
          return mergeFrom((protocol.Data.ChatData.ChatItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Data.ChatData.ChatItem other) {
        if (other == protocol.Data.ChatData.ChatItem.getDefaultInstance()) return this;
        if (other.hasSendUserId()) {
          bitField0_ |= 0x00000001;
          sendUserId_ = other.sendUserId_;
          onChanged();
        }
        if (other.hasReceiveUserId()) {
          bitField0_ |= 0x00000002;
          receiveUserId_ = other.receiveUserId_;
          onChanged();
        }
        if (other.hasChatType()) {
          setChatType(other.getChatType());
        }
        if (other.hasChatBody()) {
          bitField0_ |= 0x00000008;
          chatBody_ = other.chatBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSendUserId()) {
          
          return false;
        }
        if (!hasReceiveUserId()) {
          
          return false;
        }
        if (!hasChatType()) {
          
          return false;
        }
        if (!hasChatBody()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Data.ChatData.ChatItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Data.ChatData.ChatItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string sendUserId = 1;
      private java.lang.Object sendUserId_ = "";
      /**
       * <code>required string sendUserId = 1;</code>
       */
      public boolean hasSendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sendUserId = 1;</code>
       */
      public java.lang.String getSendUserId() {
        java.lang.Object ref = sendUserId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sendUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sendUserId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSendUserIdBytes() {
        java.lang.Object ref = sendUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sendUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sendUserId = 1;</code>
       */
      public Builder setSendUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sendUserId = 1;</code>
       */
      public Builder clearSendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sendUserId_ = getDefaultInstance().getSendUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sendUserId = 1;</code>
       */
      public Builder setSendUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sendUserId_ = value;
        onChanged();
        return this;
      }

      // required string receiveUserId = 2;
      private java.lang.Object receiveUserId_ = "";
      /**
       * <code>required string receiveUserId = 2;</code>
       */
      public boolean hasReceiveUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string receiveUserId = 2;</code>
       */
      public java.lang.String getReceiveUserId() {
        java.lang.Object ref = receiveUserId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          receiveUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string receiveUserId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getReceiveUserIdBytes() {
        java.lang.Object ref = receiveUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiveUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string receiveUserId = 2;</code>
       */
      public Builder setReceiveUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiveUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string receiveUserId = 2;</code>
       */
      public Builder clearReceiveUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        receiveUserId_ = getDefaultInstance().getReceiveUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string receiveUserId = 2;</code>
       */
      public Builder setReceiveUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        receiveUserId_ = value;
        onChanged();
        return this;
      }

      // required .protocol.ChatItem.ChatType chatType = 3;
      private protocol.Data.ChatData.ChatItem.ChatType chatType_ = protocol.Data.ChatData.ChatItem.ChatType.TEXT;
      /**
       * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
       */
      public boolean hasChatType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
       */
      public protocol.Data.ChatData.ChatItem.ChatType getChatType() {
        return chatType_;
      }
      /**
       * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
       */
      public Builder setChatType(protocol.Data.ChatData.ChatItem.ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.ChatItem.ChatType chatType = 3;</code>
       */
      public Builder clearChatType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        chatType_ = protocol.Data.ChatData.ChatItem.ChatType.TEXT;
        onChanged();
        return this;
      }

      // required string chatBody = 4;
      private java.lang.Object chatBody_ = "";
      /**
       * <code>required string chatBody = 4;</code>
       */
      public boolean hasChatBody() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string chatBody = 4;</code>
       */
      public java.lang.String getChatBody() {
        java.lang.Object ref = chatBody_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          chatBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string chatBody = 4;</code>
       */
      public com.google.protobuf.ByteString
          getChatBodyBytes() {
        java.lang.Object ref = chatBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string chatBody = 4;</code>
       */
      public Builder setChatBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        chatBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string chatBody = 4;</code>
       */
      public Builder clearChatBody() {
        bitField0_ = (bitField0_ & ~0x00000008);
        chatBody_ = getDefaultInstance().getChatBody();
        onChanged();
        return this;
      }
      /**
       * <code>required string chatBody = 4;</code>
       */
      public Builder setChatBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        chatBody_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ChatItem)
    }

    static {
      defaultInstance = new ChatItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ChatItem)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChatItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ChatItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ChatData.proto\022\010protocol\"\227\001\n\010ChatItem\022" +
      "\022\n\nsendUserId\030\001 \002(\t\022\025\n\rreceiveUserId\030\002 \002" +
      "(\t\022-\n\010chatType\030\003 \002(\0162\033.protocol.ChatItem" +
      ".ChatType\022\020\n\010chatBody\030\004 \002(\t\"\037\n\010ChatType\022" +
      "\010\n\004TEXT\020\000\022\t\n\005IMAGE\020\001B\017\n\rprotocol.Data"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_ChatItem_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_ChatItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_ChatItem_descriptor,
              new java.lang.String[] { "SendUserId", "ReceiveUserId", "ChatType", "ChatBody", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
