// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddFriendMsg.proto

package protocol;

public final class AddFriendMsg {
  private AddFriendMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddFriendReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string friendUserId = 1;
    /**
     * <code>required string friendUserId = 1;</code>
     */
    boolean hasFriendUserId();
    /**
     * <code>required string friendUserId = 1;</code>
     */
    java.lang.String getFriendUserId();
    /**
     * <code>required string friendUserId = 1;</code>
     */
    com.google.protobuf.ByteString
        getFriendUserIdBytes();
  }
  /**
   * Protobuf type {@code protocol.AddFriendReq}
   */
  public static final class AddFriendReq extends
      com.google.protobuf.GeneratedMessage
      implements AddFriendReqOrBuilder {
    // Use AddFriendReq.newBuilder() to construct.
    private AddFriendReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFriendReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFriendReq defaultInstance;
    public static AddFriendReq getDefaultInstance() {
      return defaultInstance;
    }

    public AddFriendReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFriendReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              friendUserId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.AddFriendMsg.internal_static_protocol_AddFriendReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.AddFriendMsg.internal_static_protocol_AddFriendReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.AddFriendMsg.AddFriendReq.class, protocol.AddFriendMsg.AddFriendReq.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFriendReq> PARSER =
        new com.google.protobuf.AbstractParser<AddFriendReq>() {
      public AddFriendReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFriendReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFriendReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string friendUserId = 1;
    public static final int FRIENDUSERID_FIELD_NUMBER = 1;
    private java.lang.Object friendUserId_;
    /**
     * <code>required string friendUserId = 1;</code>
     */
    public boolean hasFriendUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string friendUserId = 1;</code>
     */
    public java.lang.String getFriendUserId() {
      java.lang.Object ref = friendUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          friendUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string friendUserId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFriendUserIdBytes() {
      java.lang.Object ref = friendUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        friendUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      friendUserId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFriendUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFriendUserIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFriendUserIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.AddFriendMsg.AddFriendReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.AddFriendMsg.AddFriendReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.AddFriendMsg.AddFriendReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.AddFriendReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.AddFriendMsg.AddFriendReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.AddFriendMsg.internal_static_protocol_AddFriendReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.AddFriendMsg.internal_static_protocol_AddFriendReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.AddFriendMsg.AddFriendReq.class, protocol.AddFriendMsg.AddFriendReq.Builder.class);
      }

      // Construct using protocol.AddFriendMsg.AddFriendReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        friendUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.AddFriendMsg.internal_static_protocol_AddFriendReq_descriptor;
      }

      public protocol.AddFriendMsg.AddFriendReq getDefaultInstanceForType() {
        return protocol.AddFriendMsg.AddFriendReq.getDefaultInstance();
      }

      public protocol.AddFriendMsg.AddFriendReq build() {
        protocol.AddFriendMsg.AddFriendReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.AddFriendMsg.AddFriendReq buildPartial() {
        protocol.AddFriendMsg.AddFriendReq result = new protocol.AddFriendMsg.AddFriendReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.friendUserId_ = friendUserId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.AddFriendMsg.AddFriendReq) {
          return mergeFrom((protocol.AddFriendMsg.AddFriendReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.AddFriendMsg.AddFriendReq other) {
        if (other == protocol.AddFriendMsg.AddFriendReq.getDefaultInstance()) return this;
        if (other.hasFriendUserId()) {
          bitField0_ |= 0x00000001;
          friendUserId_ = other.friendUserId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFriendUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.AddFriendMsg.AddFriendReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.AddFriendMsg.AddFriendReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string friendUserId = 1;
      private java.lang.Object friendUserId_ = "";
      /**
       * <code>required string friendUserId = 1;</code>
       */
      public boolean hasFriendUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string friendUserId = 1;</code>
       */
      public java.lang.String getFriendUserId() {
        java.lang.Object ref = friendUserId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          friendUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string friendUserId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFriendUserIdBytes() {
        java.lang.Object ref = friendUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          friendUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string friendUserId = 1;</code>
       */
      public Builder setFriendUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        friendUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string friendUserId = 1;</code>
       */
      public Builder clearFriendUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        friendUserId_ = getDefaultInstance().getFriendUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string friendUserId = 1;</code>
       */
      public Builder setFriendUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        friendUserId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.AddFriendReq)
    }

    static {
      defaultInstance = new AddFriendReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.AddFriendReq)
  }

  public interface AddFriendRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.AddFriendRsp.ResultCode resultCode = 1;
    /**
     * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
     */
    protocol.AddFriendMsg.AddFriendRsp.ResultCode getResultCode();
  }
  /**
   * Protobuf type {@code protocol.AddFriendRsp}
   */
  public static final class AddFriendRsp extends
      com.google.protobuf.GeneratedMessage
      implements AddFriendRspOrBuilder {
    // Use AddFriendRsp.newBuilder() to construct.
    private AddFriendRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AddFriendRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AddFriendRsp defaultInstance;
    public static AddFriendRsp getDefaultInstance() {
      return defaultInstance;
    }

    public AddFriendRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AddFriendRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.AddFriendMsg.AddFriendRsp.ResultCode value = protocol.AddFriendMsg.AddFriendRsp.ResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.AddFriendMsg.internal_static_protocol_AddFriendRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.AddFriendMsg.internal_static_protocol_AddFriendRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.AddFriendMsg.AddFriendRsp.class, protocol.AddFriendMsg.AddFriendRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<AddFriendRsp> PARSER =
        new com.google.protobuf.AbstractParser<AddFriendRsp>() {
      public AddFriendRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddFriendRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AddFriendRsp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.AddFriendRsp.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.AddFriendMsg.AddFriendRsp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.AddFriendRsp.ResultCode)
    }

    private int bitField0_;
    // required .protocol.AddFriendRsp.ResultCode resultCode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private protocol.AddFriendMsg.AddFriendRsp.ResultCode resultCode_;
    /**
     * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
     */
    public protocol.AddFriendMsg.AddFriendRsp.ResultCode getResultCode() {
      return resultCode_;
    }

    private void initFields() {
      resultCode_ = protocol.AddFriendMsg.AddFriendRsp.ResultCode.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.AddFriendMsg.AddFriendRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.AddFriendMsg.AddFriendRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.AddFriendRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.AddFriendMsg.AddFriendRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.AddFriendMsg.internal_static_protocol_AddFriendRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.AddFriendMsg.internal_static_protocol_AddFriendRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.AddFriendMsg.AddFriendRsp.class, protocol.AddFriendMsg.AddFriendRsp.Builder.class);
      }

      // Construct using protocol.AddFriendMsg.AddFriendRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = protocol.AddFriendMsg.AddFriendRsp.ResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.AddFriendMsg.internal_static_protocol_AddFriendRsp_descriptor;
      }

      public protocol.AddFriendMsg.AddFriendRsp getDefaultInstanceForType() {
        return protocol.AddFriendMsg.AddFriendRsp.getDefaultInstance();
      }

      public protocol.AddFriendMsg.AddFriendRsp build() {
        protocol.AddFriendMsg.AddFriendRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.AddFriendMsg.AddFriendRsp buildPartial() {
        protocol.AddFriendMsg.AddFriendRsp result = new protocol.AddFriendMsg.AddFriendRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.AddFriendMsg.AddFriendRsp) {
          return mergeFrom((protocol.AddFriendMsg.AddFriendRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.AddFriendMsg.AddFriendRsp other) {
        if (other == protocol.AddFriendMsg.AddFriendRsp.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.AddFriendMsg.AddFriendRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.AddFriendMsg.AddFriendRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.AddFriendRsp.ResultCode resultCode = 1;
      private protocol.AddFriendMsg.AddFriendRsp.ResultCode resultCode_ = protocol.AddFriendMsg.AddFriendRsp.ResultCode.SUCCESS;
      /**
       * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
       */
      public protocol.AddFriendMsg.AddFriendRsp.ResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(protocol.AddFriendMsg.AddFriendRsp.ResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.AddFriendRsp.ResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = protocol.AddFriendMsg.AddFriendRsp.ResultCode.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.AddFriendRsp)
    }

    static {
      defaultInstance = new AddFriendRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.AddFriendRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_AddFriendReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_AddFriendReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_AddFriendRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_AddFriendRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022AddFriendMsg.proto\022\010protocol\"$\n\014AddFri" +
      "endReq\022\024\n\014friendUserId\030\001 \002(\t\"j\n\014AddFrien" +
      "dRsp\0225\n\nresultCode\030\001 \002(\0162!.protocol.AddF" +
      "riendRsp.ResultCode\"#\n\nResultCode\022\013\n\007SUC" +
      "CESS\020\000\022\010\n\004FAIL\020\001B\n\n\010protocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_AddFriendReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_AddFriendReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_AddFriendReq_descriptor,
              new java.lang.String[] { "FriendUserId", });
          internal_static_protocol_AddFriendRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_AddFriendRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_AddFriendRsp_descriptor,
              new java.lang.String[] { "ResultCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
