// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeFriendMsg.proto

package protocol.Msg;

public final class ChangeFriendMsg {
  private ChangeFriendMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChangeFriendSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.ChangeFriendSync.ChangeType changeType = 1;
    /**
     * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
     */
    boolean hasChangeType();
    /**
     * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
     */
    protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType getChangeType();

    // required .protocol.UserItem userItem = 2;
    /**
     * <code>required .protocol.UserItem userItem = 2;</code>
     */
    boolean hasUserItem();
    /**
     * <code>required .protocol.UserItem userItem = 2;</code>
     */
    protocol.Data.UserData.UserItem getUserItem();
    /**
     * <code>required .protocol.UserItem userItem = 2;</code>
     */
    protocol.Data.UserData.UserItemOrBuilder getUserItemOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.ChangeFriendSync}
   */
  public static final class ChangeFriendSync extends
      com.google.protobuf.GeneratedMessage
      implements ChangeFriendSyncOrBuilder {
    // Use ChangeFriendSync.newBuilder() to construct.
    private ChangeFriendSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChangeFriendSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChangeFriendSync defaultInstance;
    public static ChangeFriendSync getDefaultInstance() {
      return defaultInstance;
    }

    public ChangeFriendSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeFriendSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType value = protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                changeType_ = value;
              }
              break;
            }
            case 18: {
              protocol.Data.UserData.UserItem.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = userItem_.toBuilder();
              }
              userItem_ = input.readMessage(protocol.Data.UserData.UserItem.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userItem_);
                userItem_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.ChangeFriendMsg.internal_static_protocol_ChangeFriendSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.ChangeFriendMsg.internal_static_protocol_ChangeFriendSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.ChangeFriendMsg.ChangeFriendSync.class, protocol.Msg.ChangeFriendMsg.ChangeFriendSync.Builder.class);
    }

    public static com.google.protobuf.Parser<ChangeFriendSync> PARSER =
        new com.google.protobuf.AbstractParser<ChangeFriendSync>() {
      public ChangeFriendSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeFriendSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeFriendSync> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.ChangeFriendSync.ChangeType}
     */
    public enum ChangeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 0;</code>
       */
      ADD(0, 0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1, 1),
      /**
       * <code>UPDATE = 2;</code>
       */
      UPDATE(2, 2),
      ;

      /**
       * <code>ADD = 0;</code>
       */
      public static final int ADD_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;
      /**
       * <code>UPDATE = 2;</code>
       */
      public static final int UPDATE_VALUE = 2;


      public final int getNumber() { return value; }

      public static ChangeType valueOf(int value) {
        switch (value) {
          case 0: return ADD;
          case 1: return DELETE;
          case 2: return UPDATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChangeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ChangeType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChangeType>() {
              public ChangeType findValueByNumber(int number) {
                return ChangeType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.ChangeFriendMsg.ChangeFriendSync.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChangeType[] VALUES = values();

      public static ChangeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ChangeType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ChangeFriendSync.ChangeType)
    }

    private int bitField0_;
    // required .protocol.ChangeFriendSync.ChangeType changeType = 1;
    public static final int CHANGETYPE_FIELD_NUMBER = 1;
    private protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType changeType_;
    /**
     * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
     */
    public boolean hasChangeType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
     */
    public protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType getChangeType() {
      return changeType_;
    }

    // required .protocol.UserItem userItem = 2;
    public static final int USERITEM_FIELD_NUMBER = 2;
    private protocol.Data.UserData.UserItem userItem_;
    /**
     * <code>required .protocol.UserItem userItem = 2;</code>
     */
    public boolean hasUserItem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protocol.UserItem userItem = 2;</code>
     */
    public protocol.Data.UserData.UserItem getUserItem() {
      return userItem_;
    }
    /**
     * <code>required .protocol.UserItem userItem = 2;</code>
     */
    public protocol.Data.UserData.UserItemOrBuilder getUserItemOrBuilder() {
      return userItem_;
    }

    private void initFields() {
      changeType_ = protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType.ADD;
      userItem_ = protocol.Data.UserData.UserItem.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChangeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserItem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserItem().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, changeType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, userItem_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, changeType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, userItem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeFriendMsg.ChangeFriendSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.ChangeFriendMsg.ChangeFriendSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ChangeFriendSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.ChangeFriendMsg.ChangeFriendSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.ChangeFriendMsg.internal_static_protocol_ChangeFriendSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.ChangeFriendMsg.internal_static_protocol_ChangeFriendSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.ChangeFriendMsg.ChangeFriendSync.class, protocol.Msg.ChangeFriendMsg.ChangeFriendSync.Builder.class);
      }

      // Construct using protocol.Msg.ChangeFriendMsg.ChangeFriendSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        changeType_ = protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType.ADD;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userItemBuilder_ == null) {
          userItem_ = protocol.Data.UserData.UserItem.getDefaultInstance();
        } else {
          userItemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.ChangeFriendMsg.internal_static_protocol_ChangeFriendSync_descriptor;
      }

      public protocol.Msg.ChangeFriendMsg.ChangeFriendSync getDefaultInstanceForType() {
        return protocol.Msg.ChangeFriendMsg.ChangeFriendSync.getDefaultInstance();
      }

      public protocol.Msg.ChangeFriendMsg.ChangeFriendSync build() {
        protocol.Msg.ChangeFriendMsg.ChangeFriendSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.ChangeFriendMsg.ChangeFriendSync buildPartial() {
        protocol.Msg.ChangeFriendMsg.ChangeFriendSync result = new protocol.Msg.ChangeFriendMsg.ChangeFriendSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.changeType_ = changeType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (userItemBuilder_ == null) {
          result.userItem_ = userItem_;
        } else {
          result.userItem_ = userItemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.ChangeFriendMsg.ChangeFriendSync) {
          return mergeFrom((protocol.Msg.ChangeFriendMsg.ChangeFriendSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.ChangeFriendMsg.ChangeFriendSync other) {
        if (other == protocol.Msg.ChangeFriendMsg.ChangeFriendSync.getDefaultInstance()) return this;
        if (other.hasChangeType()) {
          setChangeType(other.getChangeType());
        }
        if (other.hasUserItem()) {
          mergeUserItem(other.getUserItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChangeType()) {
          
          return false;
        }
        if (!hasUserItem()) {
          
          return false;
        }
        if (!getUserItem().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.ChangeFriendMsg.ChangeFriendSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.ChangeFriendMsg.ChangeFriendSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.ChangeFriendSync.ChangeType changeType = 1;
      private protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType changeType_ = protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType.ADD;
      /**
       * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
       */
      public boolean hasChangeType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
       */
      public protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType getChangeType() {
        return changeType_;
      }
      /**
       * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
       */
      public Builder setChangeType(protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        changeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.ChangeFriendSync.ChangeType changeType = 1;</code>
       */
      public Builder clearChangeType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        changeType_ = protocol.Msg.ChangeFriendMsg.ChangeFriendSync.ChangeType.ADD;
        onChanged();
        return this;
      }

      // required .protocol.UserItem userItem = 2;
      private protocol.Data.UserData.UserItem userItem_ = protocol.Data.UserData.UserItem.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder> userItemBuilder_;
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public boolean hasUserItem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public protocol.Data.UserData.UserItem getUserItem() {
        if (userItemBuilder_ == null) {
          return userItem_;
        } else {
          return userItemBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public Builder setUserItem(protocol.Data.UserData.UserItem value) {
        if (userItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userItem_ = value;
          onChanged();
        } else {
          userItemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public Builder setUserItem(
          protocol.Data.UserData.UserItem.Builder builderForValue) {
        if (userItemBuilder_ == null) {
          userItem_ = builderForValue.build();
          onChanged();
        } else {
          userItemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public Builder mergeUserItem(protocol.Data.UserData.UserItem value) {
        if (userItemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              userItem_ != protocol.Data.UserData.UserItem.getDefaultInstance()) {
            userItem_ =
              protocol.Data.UserData.UserItem.newBuilder(userItem_).mergeFrom(value).buildPartial();
          } else {
            userItem_ = value;
          }
          onChanged();
        } else {
          userItemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public Builder clearUserItem() {
        if (userItemBuilder_ == null) {
          userItem_ = protocol.Data.UserData.UserItem.getDefaultInstance();
          onChanged();
        } else {
          userItemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public protocol.Data.UserData.UserItem.Builder getUserItemBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getUserItemFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      public protocol.Data.UserData.UserItemOrBuilder getUserItemOrBuilder() {
        if (userItemBuilder_ != null) {
          return userItemBuilder_.getMessageOrBuilder();
        } else {
          return userItem_;
        }
      }
      /**
       * <code>required .protocol.UserItem userItem = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder> 
          getUserItemFieldBuilder() {
        if (userItemBuilder_ == null) {
          userItemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder>(
                  userItem_,
                  getParentForChildren(),
                  isClean());
          userItem_ = null;
        }
        return userItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ChangeFriendSync)
    }

    static {
      defaultInstance = new ChangeFriendSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ChangeFriendSync)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChangeFriendSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ChangeFriendSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ChangeFriendMsg.proto\022\010protocol\032\016UserD" +
      "ata.proto\"\242\001\n\020ChangeFriendSync\0229\n\nchange" +
      "Type\030\001 \002(\0162%.protocol.ChangeFriendSync.C" +
      "hangeType\022$\n\010userItem\030\002 \002(\0132\022.protocol.U" +
      "serItem\"-\n\nChangeType\022\007\n\003ADD\020\000\022\n\n\006DELETE" +
      "\020\001\022\n\n\006UPDATE\020\002B\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_ChangeFriendSync_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_ChangeFriendSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_ChangeFriendSync_descriptor,
              new java.lang.String[] { "ChangeType", "UserItem", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Data.UserData.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
