// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeGroupMsg.proto

package protocol.Msg;

public final class ChangeGroupMsg {
  private ChangeGroupMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChangeGroupChatMemberReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string groupId = 1;
    /**
     * <code>required string groupId = 1;</code>
     */
    boolean hasGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    // required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;
    /**
     * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
     */
    boolean hasChangeType();
    /**
     * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
     */
    protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType getChangeType();

    // repeated string userId = 3;
    /**
     * <code>repeated string userId = 3;</code>
     */
    java.util.List<java.lang.String>
    getUserIdList();
    /**
     * <code>repeated string userId = 3;</code>
     */
    int getUserIdCount();
    /**
     * <code>repeated string userId = 3;</code>
     */
    java.lang.String getUserId(int index);
    /**
     * <code>repeated string userId = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes(int index);

    // optional string groupName = 4;
    /**
     * <code>optional string groupName = 4;</code>
     */
    boolean hasGroupName();
    /**
     * <code>optional string groupName = 4;</code>
     */
    java.lang.String getGroupName();
    /**
     * <code>optional string groupName = 4;</code>
     */
    com.google.protobuf.ByteString
        getGroupNameBytes();
  }
  /**
   * Protobuf type {@code protocol.ChangeGroupChatMemberReq}
   */
  public static final class ChangeGroupChatMemberReq extends
      com.google.protobuf.GeneratedMessage
      implements ChangeGroupChatMemberReqOrBuilder {
    // Use ChangeGroupChatMemberReq.newBuilder() to construct.
    private ChangeGroupChatMemberReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChangeGroupChatMemberReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChangeGroupChatMemberReq defaultInstance;
    public static ChangeGroupChatMemberReq getDefaultInstance() {
      return defaultInstance;
    }

    public ChangeGroupChatMemberReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeGroupChatMemberReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              groupId_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType value = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                changeType_ = value;
              }
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                userId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              userId_.add(input.readBytes());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              groupName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          userId_ = new com.google.protobuf.UnmodifiableLazyStringList(userId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.class, protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ChangeGroupChatMemberReq> PARSER =
        new com.google.protobuf.AbstractParser<ChangeGroupChatMemberReq>() {
      public ChangeGroupChatMemberReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeGroupChatMemberReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeGroupChatMemberReq> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.ChangeGroupChatMemberReq.ChangeType}
     */
    public enum ChangeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 0;</code>
       */
      ADD(0, 0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1, 1),
      /**
       * <code>UPDATE = 2;</code>
       */
      UPDATE(2, 2),
      ;

      /**
       * <code>ADD = 0;</code>
       */
      public static final int ADD_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;
      /**
       * <code>UPDATE = 2;</code>
       */
      public static final int UPDATE_VALUE = 2;


      public final int getNumber() { return value; }

      public static ChangeType valueOf(int value) {
        switch (value) {
          case 0: return ADD;
          case 1: return DELETE;
          case 2: return UPDATE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChangeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ChangeType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChangeType>() {
              public ChangeType findValueByNumber(int number) {
                return ChangeType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.getDescriptor().getEnumTypes().get(0);
      }

      private static final ChangeType[] VALUES = values();

      public static ChangeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ChangeType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ChangeGroupChatMemberReq.ChangeType)
    }

    private int bitField0_;
    // required string groupId = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private java.lang.Object groupId_;
    /**
     * <code>required string groupId = 1;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;
    public static final int CHANGETYPE_FIELD_NUMBER = 2;
    private protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType changeType_;
    /**
     * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
     */
    public boolean hasChangeType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
     */
    public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType getChangeType() {
      return changeType_;
    }

    // repeated string userId = 3;
    public static final int USERID_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList userId_;
    /**
     * <code>repeated string userId = 3;</code>
     */
    public java.util.List<java.lang.String>
        getUserIdList() {
      return userId_;
    }
    /**
     * <code>repeated string userId = 3;</code>
     */
    public int getUserIdCount() {
      return userId_.size();
    }
    /**
     * <code>repeated string userId = 3;</code>
     */
    public java.lang.String getUserId(int index) {
      return userId_.get(index);
    }
    /**
     * <code>repeated string userId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes(int index) {
      return userId_.getByteString(index);
    }

    // optional string groupName = 4;
    public static final int GROUPNAME_FIELD_NUMBER = 4;
    private java.lang.Object groupName_;
    /**
     * <code>optional string groupName = 4;</code>
     */
    public boolean hasGroupName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string groupName = 4;</code>
     */
    public java.lang.String getGroupName() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string groupName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getGroupNameBytes() {
      java.lang.Object ref = groupName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      groupId_ = "";
      changeType_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType.ADD;
      userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      groupName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChangeType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, changeType_.getNumber());
      }
      for (int i = 0; i < userId_.size(); i++) {
        output.writeBytes(3, userId_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getGroupNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, changeType_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(userId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUserIdList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getGroupNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ChangeGroupChatMemberReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.class, protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.Builder.class);
      }

      // Construct using protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        changeType_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType.ADD;
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        groupName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberReq_descriptor;
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq getDefaultInstanceForType() {
        return protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.getDefaultInstance();
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq build() {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq buildPartial() {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq result = new protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.changeType_ = changeType_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          userId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              userId_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.groupName_ = groupName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq) {
          return mergeFrom((protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq other) {
        if (other == protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.getDefaultInstance()) return this;
        if (other.hasGroupId()) {
          bitField0_ |= 0x00000001;
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.hasChangeType()) {
          setChangeType(other.getChangeType());
        }
        if (!other.userId_.isEmpty()) {
          if (userId_.isEmpty()) {
            userId_ = other.userId_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureUserIdIsMutable();
            userId_.addAll(other.userId_);
          }
          onChanged();
        }
        if (other.hasGroupName()) {
          bitField0_ |= 0x00000008;
          groupName_ = other.groupName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupId()) {
          
          return false;
        }
        if (!hasChangeType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string groupId = 1;
      private java.lang.Object groupId_ = "";
      /**
       * <code>required string groupId = 1;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }

      // required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;
      private protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType changeType_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType.ADD;
      /**
       * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
       */
      public boolean hasChangeType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
       */
      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType getChangeType() {
        return changeType_;
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
       */
      public Builder setChangeType(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        changeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberReq.ChangeType changeType = 2;</code>
       */
      public Builder clearChangeType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        changeType_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberReq.ChangeType.ADD;
        onChanged();
        return this;
      }

      // repeated string userId = 3;
      private com.google.protobuf.LazyStringList userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserIdIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          userId_ = new com.google.protobuf.LazyStringArrayList(userId_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public java.util.List<java.lang.String>
          getUserIdList() {
        return java.util.Collections.unmodifiableList(userId_);
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public int getUserIdCount() {
        return userId_.size();
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public java.lang.String getUserId(int index) {
        return userId_.get(index);
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes(int index) {
        return userId_.getByteString(index);
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public Builder setUserId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public Builder addUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public Builder addAllUserId(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserIdIsMutable();
        super.addAll(values, userId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public Builder clearUserId() {
        userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 3;</code>
       */
      public Builder addUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }

      // optional string groupName = 4;
      private java.lang.Object groupName_ = "";
      /**
       * <code>optional string groupName = 4;</code>
       */
      public boolean hasGroupName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string groupName = 4;</code>
       */
      public java.lang.String getGroupName() {
        java.lang.Object ref = groupName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string groupName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getGroupNameBytes() {
        java.lang.Object ref = groupName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string groupName = 4;</code>
       */
      public Builder setGroupName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        groupName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupName = 4;</code>
       */
      public Builder clearGroupName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupName_ = getDefaultInstance().getGroupName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string groupName = 4;</code>
       */
      public Builder setGroupNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        groupName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ChangeGroupChatMemberReq)
    }

    static {
      defaultInstance = new ChangeGroupChatMemberReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ChangeGroupChatMemberReq)
  }

  public interface ChangeGroupChatMemberRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;
    /**
     * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
     */
    protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode getResultCode();
  }
  /**
   * Protobuf type {@code protocol.ChangeGroupChatMemberRsp}
   */
  public static final class ChangeGroupChatMemberRsp extends
      com.google.protobuf.GeneratedMessage
      implements ChangeGroupChatMemberRspOrBuilder {
    // Use ChangeGroupChatMemberRsp.newBuilder() to construct.
    private ChangeGroupChatMemberRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChangeGroupChatMemberRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChangeGroupChatMemberRsp defaultInstance;
    public static ChangeGroupChatMemberRsp getDefaultInstance() {
      return defaultInstance;
    }

    public ChangeGroupChatMemberRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeGroupChatMemberRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode value = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.class, protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<ChangeGroupChatMemberRsp> PARSER =
        new com.google.protobuf.AbstractParser<ChangeGroupChatMemberRsp>() {
      public ChangeGroupChatMemberRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeGroupChatMemberRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeGroupChatMemberRsp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.ChangeGroupChatMemberRsp.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      /**
       * <code>NO_AUTHORITY = 2;</code>
       */
      NO_AUTHORITY(2, 2),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;
      /**
       * <code>NO_AUTHORITY = 2;</code>
       */
      public static final int NO_AUTHORITY_VALUE = 2;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          case 2: return NO_AUTHORITY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ChangeGroupChatMemberRsp.ResultCode)
    }

    private int bitField0_;
    // required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode resultCode_;
    /**
     * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
     */
    public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode getResultCode() {
      return resultCode_;
    }

    private void initFields() {
      resultCode_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ChangeGroupChatMemberRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.class, protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.Builder.class);
      }

      // Construct using protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberRsp_descriptor;
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp getDefaultInstanceForType() {
        return protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.getDefaultInstance();
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp build() {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp buildPartial() {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp result = new protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp) {
          return mergeFrom((protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp other) {
        if (other == protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;
      private protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode resultCode_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode.SUCCESS;
      /**
       * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
       */
      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberRsp.ResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberRsp.ResultCode.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ChangeGroupChatMemberRsp)
    }

    static {
      defaultInstance = new ChangeGroupChatMemberRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ChangeGroupChatMemberRsp)
  }

  public interface ChangeGroupChatMemberSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.ChangeGroupChatMemberSync.Type type = 1;
    /**
     * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
     */
    protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type getType();

    // repeated string userId = 2;
    /**
     * <code>repeated string userId = 2;</code>
     */
    java.util.List<java.lang.String>
    getUserIdList();
    /**
     * <code>repeated string userId = 2;</code>
     */
    int getUserIdCount();
    /**
     * <code>repeated string userId = 2;</code>
     */
    java.lang.String getUserId(int index);
    /**
     * <code>repeated string userId = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes(int index);
  }
  /**
   * Protobuf type {@code protocol.ChangeGroupChatMemberSync}
   */
  public static final class ChangeGroupChatMemberSync extends
      com.google.protobuf.GeneratedMessage
      implements ChangeGroupChatMemberSyncOrBuilder {
    // Use ChangeGroupChatMemberSync.newBuilder() to construct.
    private ChangeGroupChatMemberSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChangeGroupChatMemberSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChangeGroupChatMemberSync defaultInstance;
    public static ChangeGroupChatMemberSync getDefaultInstance() {
      return defaultInstance;
    }

    public ChangeGroupChatMemberSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChangeGroupChatMemberSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type value = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                userId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              userId_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          userId_ = new com.google.protobuf.UnmodifiableLazyStringList(userId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.class, protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Builder.class);
    }

    public static com.google.protobuf.Parser<ChangeGroupChatMemberSync> PARSER =
        new com.google.protobuf.AbstractParser<ChangeGroupChatMemberSync>() {
      public ChangeGroupChatMemberSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChangeGroupChatMemberSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChangeGroupChatMemberSync> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.ChangeGroupChatMemberSync.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 0;</code>
       */
      ADD(0, 0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1, 1),
      /**
       * <code>REFRESH = 2;</code>
       */
      REFRESH(2, 2),
      ;

      /**
       * <code>ADD = 0;</code>
       */
      public static final int ADD_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;
      /**
       * <code>REFRESH = 2;</code>
       */
      public static final int REFRESH_VALUE = 2;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return ADD;
          case 1: return DELETE;
          case 2: return REFRESH;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.ChangeGroupChatMemberSync.Type)
    }

    private int bitField0_;
    // required .protocol.ChangeGroupChatMemberSync.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type type_;
    /**
     * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
     */
    public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type getType() {
      return type_;
    }

    // repeated string userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList userId_;
    /**
     * <code>repeated string userId = 2;</code>
     */
    public java.util.List<java.lang.String>
        getUserIdList() {
      return userId_;
    }
    /**
     * <code>repeated string userId = 2;</code>
     */
    public int getUserIdCount() {
      return userId_.size();
    }
    /**
     * <code>repeated string userId = 2;</code>
     */
    public java.lang.String getUserId(int index) {
      return userId_.get(index);
    }
    /**
     * <code>repeated string userId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes(int index) {
      return userId_.getByteString(index);
    }

    private void initFields() {
      type_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type.ADD;
      userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < userId_.size(); i++) {
        output.writeBytes(2, userId_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < userId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(userId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUserIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ChangeGroupChatMemberSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.class, protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Builder.class);
      }

      // Construct using protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type.ADD;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.ChangeGroupMsg.internal_static_protocol_ChangeGroupChatMemberSync_descriptor;
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync getDefaultInstanceForType() {
        return protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.getDefaultInstance();
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync build() {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync buildPartial() {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync result = new protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          userId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              userId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync) {
          return mergeFrom((protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync other) {
        if (other == protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.userId_.isEmpty()) {
          if (userId_.isEmpty()) {
            userId_ = other.userId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUserIdIsMutable();
            userId_.addAll(other.userId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.ChangeGroupChatMemberSync.Type type = 1;
      private protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type type_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type.ADD;
      /**
       * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
       */
      public protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type getType() {
        return type_;
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
       */
      public Builder setType(protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.ChangeGroupChatMemberSync.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = protocol.Msg.ChangeGroupMsg.ChangeGroupChatMemberSync.Type.ADD;
        onChanged();
        return this;
      }

      // repeated string userId = 2;
      private com.google.protobuf.LazyStringList userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          userId_ = new com.google.protobuf.LazyStringArrayList(userId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public java.util.List<java.lang.String>
          getUserIdList() {
        return java.util.Collections.unmodifiableList(userId_);
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public int getUserIdCount() {
        return userId_.size();
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public java.lang.String getUserId(int index) {
        return userId_.get(index);
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes(int index) {
        return userId_.getByteString(index);
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public Builder setUserId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public Builder addUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public Builder addAllUserId(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserIdIsMutable();
        super.addAll(values, userId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public Builder clearUserId() {
        userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 2;</code>
       */
      public Builder addUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.ChangeGroupChatMemberSync)
    }

    static {
      defaultInstance = new ChangeGroupChatMemberSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.ChangeGroupChatMemberSync)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChangeGroupChatMemberReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ChangeGroupChatMemberReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChangeGroupChatMemberRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ChangeGroupChatMemberRsp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ChangeGroupChatMemberSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_ChangeGroupChatMemberSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ChangeGroupMsg.proto\022\010protocol\"\300\001\n\030Cha" +
      "ngeGroupChatMemberReq\022\017\n\007groupId\030\001 \002(\t\022A" +
      "\n\nchangeType\030\002 \002(\0162-.protocol.ChangeGrou" +
      "pChatMemberReq.ChangeType\022\016\n\006userId\030\003 \003(" +
      "\t\022\021\n\tgroupName\030\004 \001(\t\"-\n\nChangeType\022\007\n\003AD" +
      "D\020\000\022\n\n\006DELETE\020\001\022\n\n\006UPDATE\020\002\"\224\001\n\030ChangeGr" +
      "oupChatMemberRsp\022A\n\nresultCode\030\001 \002(\0162-.p" +
      "rotocol.ChangeGroupChatMemberRsp.ResultC" +
      "ode\"5\n\nResultCode\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020\001" +
      "\022\020\n\014NO_AUTHORITY\020\002\"\215\001\n\031ChangeGroupChatMe",
      "mberSync\0226\n\004type\030\001 \002(\0162(.protocol.Change" +
      "GroupChatMemberSync.Type\022\016\n\006userId\030\002 \003(\t" +
      "\"(\n\004Type\022\007\n\003ADD\020\000\022\n\n\006DELETE\020\001\022\013\n\007REFRESH" +
      "\020\002B\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_ChangeGroupChatMemberReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_ChangeGroupChatMemberReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_ChangeGroupChatMemberReq_descriptor,
              new java.lang.String[] { "GroupId", "ChangeType", "UserId", "GroupName", });
          internal_static_protocol_ChangeGroupChatMemberRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_ChangeGroupChatMemberRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_ChangeGroupChatMemberRsp_descriptor,
              new java.lang.String[] { "ResultCode", });
          internal_static_protocol_ChangeGroupChatMemberSync_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_protocol_ChangeGroupChatMemberSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_ChangeGroupChatMemberSync_descriptor,
              new java.lang.String[] { "Type", "UserId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
