// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateGroupChatMsg.proto

package protocol.Msg;

public final class CreateGroupChatMsg {
  private CreateGroupChatMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CreateGroupChatReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string userId = 1;
    /**
     * <code>repeated string userId = 1;</code>
     */
    java.util.List<java.lang.String>
    getUserIdList();
    /**
     * <code>repeated string userId = 1;</code>
     */
    int getUserIdCount();
    /**
     * <code>repeated string userId = 1;</code>
     */
    java.lang.String getUserId(int index);
    /**
     * <code>repeated string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes(int index);
  }
  /**
   * Protobuf type {@code protocol.CreateGroupChatReq}
   */
  public static final class CreateGroupChatReq extends
      com.google.protobuf.GeneratedMessage
      implements CreateGroupChatReqOrBuilder {
    // Use CreateGroupChatReq.newBuilder() to construct.
    private CreateGroupChatReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateGroupChatReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateGroupChatReq defaultInstance;
    public static CreateGroupChatReq getDefaultInstance() {
      return defaultInstance;
    }

    public CreateGroupChatReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateGroupChatReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                userId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              userId_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          userId_ = new com.google.protobuf.UnmodifiableLazyStringList(userId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.class, protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateGroupChatReq> PARSER =
        new com.google.protobuf.AbstractParser<CreateGroupChatReq>() {
      public CreateGroupChatReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateGroupChatReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateGroupChatReq> getParserForType() {
      return PARSER;
    }

    // repeated string userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList userId_;
    /**
     * <code>repeated string userId = 1;</code>
     */
    public java.util.List<java.lang.String>
        getUserIdList() {
      return userId_;
    }
    /**
     * <code>repeated string userId = 1;</code>
     */
    public int getUserIdCount() {
      return userId_.size();
    }
    /**
     * <code>repeated string userId = 1;</code>
     */
    public java.lang.String getUserId(int index) {
      return userId_.get(index);
    }
    /**
     * <code>repeated string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes(int index) {
      return userId_.getByteString(index);
    }

    private void initFields() {
      userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < userId_.size(); i++) {
        output.writeBytes(1, userId_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < userId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(userId_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUserIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.CreateGroupChatReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.CreateGroupChatMsg.CreateGroupChatReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.class, protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.Builder.class);
      }

      // Construct using protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatReq_descriptor;
      }

      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq getDefaultInstanceForType() {
        return protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.getDefaultInstance();
      }

      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq build() {
        protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq buildPartial() {
        protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq result = new protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          userId_ = new com.google.protobuf.UnmodifiableLazyStringList(
              userId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userId_ = userId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq) {
          return mergeFrom((protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq other) {
        if (other == protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq.getDefaultInstance()) return this;
        if (!other.userId_.isEmpty()) {
          if (userId_.isEmpty()) {
            userId_ = other.userId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserIdIsMutable();
            userId_.addAll(other.userId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.CreateGroupChatMsg.CreateGroupChatReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string userId = 1;
      private com.google.protobuf.LazyStringList userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUserIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          userId_ = new com.google.protobuf.LazyStringArrayList(userId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public java.util.List<java.lang.String>
          getUserIdList() {
        return java.util.Collections.unmodifiableList(userId_);
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public int getUserIdCount() {
        return userId_.size();
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public java.lang.String getUserId(int index) {
        return userId_.get(index);
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes(int index) {
        return userId_.getByteString(index);
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public Builder setUserId(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public Builder addUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public Builder addAllUserId(
          java.lang.Iterable<java.lang.String> values) {
        ensureUserIdIsMutable();
        super.addAll(values, userId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public Builder clearUserId() {
        userId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string userId = 1;</code>
       */
      public Builder addUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUserIdIsMutable();
        userId_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.CreateGroupChatReq)
    }

    static {
      defaultInstance = new CreateGroupChatReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.CreateGroupChatReq)
  }

  public interface CreateGroupChatRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;
    /**
     * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode getResultCode();

    // required int64 groupChatId = 2;
    /**
     * <code>required int64 groupChatId = 2;</code>
     */
    boolean hasGroupChatId();
    /**
     * <code>required int64 groupChatId = 2;</code>
     */
    long getGroupChatId();
  }
  /**
   * Protobuf type {@code protocol.CreateGroupChatRsp}
   */
  public static final class CreateGroupChatRsp extends
      com.google.protobuf.GeneratedMessage
      implements CreateGroupChatRspOrBuilder {
    // Use CreateGroupChatRsp.newBuilder() to construct.
    private CreateGroupChatRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CreateGroupChatRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CreateGroupChatRsp defaultInstance;
    public static CreateGroupChatRsp getDefaultInstance() {
      return defaultInstance;
    }

    public CreateGroupChatRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CreateGroupChatRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode value = protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              groupChatId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.class, protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<CreateGroupChatRsp> PARSER =
        new com.google.protobuf.AbstractParser<CreateGroupChatRsp>() {
      public CreateGroupChatRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateGroupChatRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CreateGroupChatRsp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.CreateGroupChatRsp.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.CreateGroupChatRsp.ResultCode)
    }

    private int bitField0_;
    // required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode resultCode_;
    /**
     * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    public protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode getResultCode() {
      return resultCode_;
    }

    // required int64 groupChatId = 2;
    public static final int GROUPCHATID_FIELD_NUMBER = 2;
    private long groupChatId_;
    /**
     * <code>required int64 groupChatId = 2;</code>
     */
    public boolean hasGroupChatId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 groupChatId = 2;</code>
     */
    public long getGroupChatId() {
      return groupChatId_;
    }

    private void initFields() {
      resultCode_ = protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode.SUCCESS;
      groupChatId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGroupChatId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, groupChatId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, groupChatId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.CreateGroupChatRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.CreateGroupChatMsg.CreateGroupChatRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.class, protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.Builder.class);
      }

      // Construct using protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        groupChatId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.CreateGroupChatMsg.internal_static_protocol_CreateGroupChatRsp_descriptor;
      }

      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp getDefaultInstanceForType() {
        return protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.getDefaultInstance();
      }

      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp build() {
        protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp buildPartial() {
        protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp result = new protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupChatId_ = groupChatId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp) {
          return mergeFrom((protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp other) {
        if (other == protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasGroupChatId()) {
          setGroupChatId(other.getGroupChatId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (!hasGroupChatId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;
      private protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode resultCode_ = protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode.SUCCESS;
      /**
       * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.CreateGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = protocol.Msg.CreateGroupChatMsg.CreateGroupChatRsp.ResultCode.SUCCESS;
        onChanged();
        return this;
      }

      // required int64 groupChatId = 2;
      private long groupChatId_ ;
      /**
       * <code>required int64 groupChatId = 2;</code>
       */
      public boolean hasGroupChatId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 groupChatId = 2;</code>
       */
      public long getGroupChatId() {
        return groupChatId_;
      }
      /**
       * <code>required int64 groupChatId = 2;</code>
       */
      public Builder setGroupChatId(long value) {
        bitField0_ |= 0x00000002;
        groupChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 groupChatId = 2;</code>
       */
      public Builder clearGroupChatId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupChatId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.CreateGroupChatRsp)
    }

    static {
      defaultInstance = new CreateGroupChatRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.CreateGroupChatRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CreateGroupChatReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_CreateGroupChatReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CreateGroupChatRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_CreateGroupChatRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030CreateGroupChatMsg.proto\022\010protocol\032\016Ch" +
      "atData.proto\"$\n\022CreateGroupChatReq\022\016\n\006us" +
      "erId\030\001 \003(\t\"\213\001\n\022CreateGroupChatRsp\022;\n\nres" +
      "ultCode\030\001 \002(\0162\'.protocol.CreateGroupChat" +
      "Rsp.ResultCode\022\023\n\013groupChatId\030\002 \002(\003\"#\n\nR" +
      "esultCode\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020\001B\016\n\014prot" +
      "ocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_CreateGroupChatReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_CreateGroupChatReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_CreateGroupChatReq_descriptor,
              new java.lang.String[] { "UserId", });
          internal_static_protocol_CreateGroupChatRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_CreateGroupChatRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_CreateGroupChatRsp_descriptor,
              new java.lang.String[] { "ResultCode", "GroupChatId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Data.ChatData.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
