// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetGroupInfoMsg.proto

package protocol.Msg;

public final class GetGroupInfoMsg {
  private GetGroupInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetGroupInfoReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string groupId = 1;
    /**
     * <code>required string groupId = 1;</code>
     */
    boolean hasGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    java.lang.String getGroupId();
    /**
     * <code>required string groupId = 1;</code>
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();
  }
  /**
   * Protobuf type {@code protocol.GetGroupInfoReq}
   */
  public static final class GetGroupInfoReq extends
      com.google.protobuf.GeneratedMessage
      implements GetGroupInfoReqOrBuilder {
    // Use GetGroupInfoReq.newBuilder() to construct.
    private GetGroupInfoReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetGroupInfoReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetGroupInfoReq defaultInstance;
    public static GetGroupInfoReq getDefaultInstance() {
      return defaultInstance;
    }

    public GetGroupInfoReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetGroupInfoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              groupId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.class, protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.Builder.class);
    }

    public static com.google.protobuf.Parser<GetGroupInfoReq> PARSER =
        new com.google.protobuf.AbstractParser<GetGroupInfoReq>() {
      public GetGroupInfoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetGroupInfoReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetGroupInfoReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string groupId = 1;
    public static final int GROUPID_FIELD_NUMBER = 1;
    private java.lang.Object groupId_;
    /**
     * <code>required string groupId = 1;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          groupId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string groupId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      groupId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGroupIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGroupIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.GetGroupInfoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.GetGroupInfoMsg.GetGroupInfoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.class, protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.Builder.class);
      }

      // Construct using protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        groupId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoReq_descriptor;
      }

      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq getDefaultInstanceForType() {
        return protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.getDefaultInstance();
      }

      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq build() {
        protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq buildPartial() {
        protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq result = new protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.groupId_ = groupId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq) {
          return mergeFrom((protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq other) {
        if (other == protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq.getDefaultInstance()) return this;
        if (other.hasGroupId()) {
          bitField0_ |= 0x00000001;
          groupId_ = other.groupId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasGroupId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.GetGroupInfoMsg.GetGroupInfoReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string groupId = 1;
      private java.lang.Object groupId_ = "";
      /**
       * <code>required string groupId = 1;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>required string groupId = 1;</code>
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        groupId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.GetGroupInfoReq)
    }

    static {
      defaultInstance = new GetGroupInfoReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.GetGroupInfoReq)
  }

  public interface GetGroupInfoRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;
    /**
     * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
     */
    protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode getResultCode();

    // required .protocol.GroupItem groupItem = 2;
    /**
     * <code>required .protocol.GroupItem groupItem = 2;</code>
     */
    boolean hasGroupItem();
    /**
     * <code>required .protocol.GroupItem groupItem = 2;</code>
     */
    protocol.Data.GroupData.GroupItem getGroupItem();
    /**
     * <code>required .protocol.GroupItem groupItem = 2;</code>
     */
    protocol.Data.GroupData.GroupItemOrBuilder getGroupItemOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.GetGroupInfoRsp}
   */
  public static final class GetGroupInfoRsp extends
      com.google.protobuf.GeneratedMessage
      implements GetGroupInfoRspOrBuilder {
    // Use GetGroupInfoRsp.newBuilder() to construct.
    private GetGroupInfoRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetGroupInfoRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetGroupInfoRsp defaultInstance;
    public static GetGroupInfoRsp getDefaultInstance() {
      return defaultInstance;
    }

    public GetGroupInfoRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetGroupInfoRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode value = protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
            case 18: {
              protocol.Data.GroupData.GroupItem.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = groupItem_.toBuilder();
              }
              groupItem_ = input.readMessage(protocol.Data.GroupData.GroupItem.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupItem_);
                groupItem_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.class, protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<GetGroupInfoRsp> PARSER =
        new com.google.protobuf.AbstractParser<GetGroupInfoRsp>() {
      public GetGroupInfoRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetGroupInfoRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetGroupInfoRsp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.GetGroupInfoRsp.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       *
       * <pre>
       *搜索到群
       * </pre>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       *
       * <pre>
       *未搜索到群
       * </pre>
       */
      FAIL(1, 1),
      /**
       * <code>GROUP_NOT_EXIST = 2;</code>
       *
       * <pre>
       *群不存在
       * </pre>
       */
      GROUP_NOT_EXIST(2, 2),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       *
       * <pre>
       *搜索到群
       * </pre>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       *
       * <pre>
       *未搜索到群
       * </pre>
       */
      public static final int FAIL_VALUE = 1;
      /**
       * <code>GROUP_NOT_EXIST = 2;</code>
       *
       * <pre>
       *群不存在
       * </pre>
       */
      public static final int GROUP_NOT_EXIST_VALUE = 2;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          case 2: return GROUP_NOT_EXIST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.GetGroupInfoRsp.ResultCode)
    }

    private int bitField0_;
    // required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode resultCode_;
    /**
     * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
     */
    public protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode getResultCode() {
      return resultCode_;
    }

    // required .protocol.GroupItem groupItem = 2;
    public static final int GROUPITEM_FIELD_NUMBER = 2;
    private protocol.Data.GroupData.GroupItem groupItem_;
    /**
     * <code>required .protocol.GroupItem groupItem = 2;</code>
     */
    public boolean hasGroupItem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .protocol.GroupItem groupItem = 2;</code>
     */
    public protocol.Data.GroupData.GroupItem getGroupItem() {
      return groupItem_;
    }
    /**
     * <code>required .protocol.GroupItem groupItem = 2;</code>
     */
    public protocol.Data.GroupData.GroupItemOrBuilder getGroupItemOrBuilder() {
      return groupItem_;
    }

    private void initFields() {
      resultCode_ = protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode.SUCCESS;
      groupItem_ = protocol.Data.GroupData.GroupItem.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGroupItem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getGroupItem().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, groupItem_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, groupItem_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.GetGroupInfoRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.GetGroupInfoMsg.GetGroupInfoRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.class, protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.Builder.class);
      }

      // Construct using protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGroupItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (groupItemBuilder_ == null) {
          groupItem_ = protocol.Data.GroupData.GroupItem.getDefaultInstance();
        } else {
          groupItemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.GetGroupInfoMsg.internal_static_protocol_GetGroupInfoRsp_descriptor;
      }

      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp getDefaultInstanceForType() {
        return protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.getDefaultInstance();
      }

      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp build() {
        protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp buildPartial() {
        protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp result = new protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (groupItemBuilder_ == null) {
          result.groupItem_ = groupItem_;
        } else {
          result.groupItem_ = groupItemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp) {
          return mergeFrom((protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp other) {
        if (other == protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasGroupItem()) {
          mergeGroupItem(other.getGroupItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        if (!hasGroupItem()) {
          
          return false;
        }
        if (!getGroupItem().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;
      private protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode resultCode_ = protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode.SUCCESS;
      /**
       * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
       */
      public protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.GetGroupInfoRsp.ResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = protocol.Msg.GetGroupInfoMsg.GetGroupInfoRsp.ResultCode.SUCCESS;
        onChanged();
        return this;
      }

      // required .protocol.GroupItem groupItem = 2;
      private protocol.Data.GroupData.GroupItem groupItem_ = protocol.Data.GroupData.GroupItem.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.GroupData.GroupItem, protocol.Data.GroupData.GroupItem.Builder, protocol.Data.GroupData.GroupItemOrBuilder> groupItemBuilder_;
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public boolean hasGroupItem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public protocol.Data.GroupData.GroupItem getGroupItem() {
        if (groupItemBuilder_ == null) {
          return groupItem_;
        } else {
          return groupItemBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public Builder setGroupItem(protocol.Data.GroupData.GroupItem value) {
        if (groupItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupItem_ = value;
          onChanged();
        } else {
          groupItemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public Builder setGroupItem(
          protocol.Data.GroupData.GroupItem.Builder builderForValue) {
        if (groupItemBuilder_ == null) {
          groupItem_ = builderForValue.build();
          onChanged();
        } else {
          groupItemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public Builder mergeGroupItem(protocol.Data.GroupData.GroupItem value) {
        if (groupItemBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              groupItem_ != protocol.Data.GroupData.GroupItem.getDefaultInstance()) {
            groupItem_ =
              protocol.Data.GroupData.GroupItem.newBuilder(groupItem_).mergeFrom(value).buildPartial();
          } else {
            groupItem_ = value;
          }
          onChanged();
        } else {
          groupItemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public Builder clearGroupItem() {
        if (groupItemBuilder_ == null) {
          groupItem_ = protocol.Data.GroupData.GroupItem.getDefaultInstance();
          onChanged();
        } else {
          groupItemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public protocol.Data.GroupData.GroupItem.Builder getGroupItemBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGroupItemFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      public protocol.Data.GroupData.GroupItemOrBuilder getGroupItemOrBuilder() {
        if (groupItemBuilder_ != null) {
          return groupItemBuilder_.getMessageOrBuilder();
        } else {
          return groupItem_;
        }
      }
      /**
       * <code>required .protocol.GroupItem groupItem = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.GroupData.GroupItem, protocol.Data.GroupData.GroupItem.Builder, protocol.Data.GroupData.GroupItemOrBuilder> 
          getGroupItemFieldBuilder() {
        if (groupItemBuilder_ == null) {
          groupItemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.Data.GroupData.GroupItem, protocol.Data.GroupData.GroupItem.Builder, protocol.Data.GroupData.GroupItemOrBuilder>(
                  groupItem_,
                  getParentForChildren(),
                  isClean());
          groupItem_ = null;
        }
        return groupItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol.GetGroupInfoRsp)
    }

    static {
      defaultInstance = new GetGroupInfoRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.GetGroupInfoRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_GetGroupInfoReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_GetGroupInfoReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_GetGroupInfoRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_GetGroupInfoRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GetGroupInfoMsg.proto\022\010protocol\032\017Group" +
      "Data.proto\"\"\n\017GetGroupInfoReq\022\017\n\007groupId" +
      "\030\001 \002(\t\"\255\001\n\017GetGroupInfoRsp\0228\n\nresultCode" +
      "\030\001 \002(\0162$.protocol.GetGroupInfoRsp.Result" +
      "Code\022&\n\tgroupItem\030\002 \002(\0132\023.protocol.Group" +
      "Item\"8\n\nResultCode\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020" +
      "\001\022\023\n\017GROUP_NOT_EXIST\020\002B\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_GetGroupInfoReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_GetGroupInfoReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_GetGroupInfoReq_descriptor,
              new java.lang.String[] { "GroupId", });
          internal_static_protocol_GetGroupInfoRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_GetGroupInfoRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_GetGroupInfoRsp_descriptor,
              new java.lang.String[] { "ResultCode", "GroupItem", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Data.GroupData.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
