// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoginInitAllInfoMsg.proto

package protocol.Msg;

public final class LoginInitAllInfoMsg {
  private LoginInitAllInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginInitAllInfoSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.UserItem userInfo = 1;
    /**
     * <code>required .protocol.UserItem userInfo = 1;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>required .protocol.UserItem userInfo = 1;</code>
     */
    protocol.Data.UserData.UserItem getUserInfo();
    /**
     * <code>required .protocol.UserItem userInfo = 1;</code>
     */
    protocol.Data.UserData.UserItemOrBuilder getUserInfoOrBuilder();

    // repeated .protocol.UserItem friends = 2;
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    java.util.List<protocol.Data.UserData.UserItem> 
        getFriendsList();
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    protocol.Data.UserData.UserItem getFriends(int index);
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    int getFriendsCount();
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    java.util.List<? extends protocol.Data.UserData.UserItemOrBuilder> 
        getFriendsOrBuilderList();
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    protocol.Data.UserData.UserItemOrBuilder getFriendsOrBuilder(
        int index);

    // repeated .protocol.GroupItem groups = 3;
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    java.util.List<protocol.Data.GroupData.GroupItem> 
        getGroupsList();
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    protocol.Data.GroupData.GroupItem getGroups(int index);
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    int getGroupsCount();
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    java.util.List<? extends protocol.Data.GroupData.GroupItemOrBuilder> 
        getGroupsOrBuilderList();
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    protocol.Data.GroupData.GroupItemOrBuilder getGroupsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocol.LoginInitAllInfoSync}
   */
  public static final class LoginInitAllInfoSync extends
      com.google.protobuf.GeneratedMessage
      implements LoginInitAllInfoSyncOrBuilder {
    // Use LoginInitAllInfoSync.newBuilder() to construct.
    private LoginInitAllInfoSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginInitAllInfoSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginInitAllInfoSync defaultInstance;
    public static LoginInitAllInfoSync getDefaultInstance() {
      return defaultInstance;
    }

    public LoginInitAllInfoSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginInitAllInfoSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.Data.UserData.UserItem.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(protocol.Data.UserData.UserItem.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                friends_ = new java.util.ArrayList<protocol.Data.UserData.UserItem>();
                mutable_bitField0_ |= 0x00000002;
              }
              friends_.add(input.readMessage(protocol.Data.UserData.UserItem.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                groups_ = new java.util.ArrayList<protocol.Data.GroupData.GroupItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              groups_.add(input.readMessage(protocol.Data.GroupData.GroupItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          friends_ = java.util.Collections.unmodifiableList(friends_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.LoginInitAllInfoMsg.internal_static_protocol_LoginInitAllInfoSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.LoginInitAllInfoMsg.internal_static_protocol_LoginInitAllInfoSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.class, protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginInitAllInfoSync> PARSER =
        new com.google.protobuf.AbstractParser<LoginInitAllInfoSync>() {
      public LoginInitAllInfoSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginInitAllInfoSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginInitAllInfoSync> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .protocol.UserItem userInfo = 1;
    public static final int USERINFO_FIELD_NUMBER = 1;
    private protocol.Data.UserData.UserItem userInfo_;
    /**
     * <code>required .protocol.UserItem userInfo = 1;</code>
     */
    public boolean hasUserInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.UserItem userInfo = 1;</code>
     */
    public protocol.Data.UserData.UserItem getUserInfo() {
      return userInfo_;
    }
    /**
     * <code>required .protocol.UserItem userInfo = 1;</code>
     */
    public protocol.Data.UserData.UserItemOrBuilder getUserInfoOrBuilder() {
      return userInfo_;
    }

    // repeated .protocol.UserItem friends = 2;
    public static final int FRIENDS_FIELD_NUMBER = 2;
    private java.util.List<protocol.Data.UserData.UserItem> friends_;
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    public java.util.List<protocol.Data.UserData.UserItem> getFriendsList() {
      return friends_;
    }
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    public java.util.List<? extends protocol.Data.UserData.UserItemOrBuilder> 
        getFriendsOrBuilderList() {
      return friends_;
    }
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    public int getFriendsCount() {
      return friends_.size();
    }
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    public protocol.Data.UserData.UserItem getFriends(int index) {
      return friends_.get(index);
    }
    /**
     * <code>repeated .protocol.UserItem friends = 2;</code>
     */
    public protocol.Data.UserData.UserItemOrBuilder getFriendsOrBuilder(
        int index) {
      return friends_.get(index);
    }

    // repeated .protocol.GroupItem groups = 3;
    public static final int GROUPS_FIELD_NUMBER = 3;
    private java.util.List<protocol.Data.GroupData.GroupItem> groups_;
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    public java.util.List<protocol.Data.GroupData.GroupItem> getGroupsList() {
      return groups_;
    }
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    public java.util.List<? extends protocol.Data.GroupData.GroupItemOrBuilder> 
        getGroupsOrBuilderList() {
      return groups_;
    }
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    public int getGroupsCount() {
      return groups_.size();
    }
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    public protocol.Data.GroupData.GroupItem getGroups(int index) {
      return groups_.get(index);
    }
    /**
     * <code>repeated .protocol.GroupItem groups = 3;</code>
     */
    public protocol.Data.GroupData.GroupItemOrBuilder getGroupsOrBuilder(
        int index) {
      return groups_.get(index);
    }

    private void initFields() {
      userInfo_ = protocol.Data.UserData.UserItem.getDefaultInstance();
      friends_ = java.util.Collections.emptyList();
      groups_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getFriendsCount(); i++) {
        if (!getFriends(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getGroupsCount(); i++) {
        if (!getGroups(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userInfo_);
      }
      for (int i = 0; i < friends_.size(); i++) {
        output.writeMessage(2, friends_.get(i));
      }
      for (int i = 0; i < groups_.size(); i++) {
        output.writeMessage(3, groups_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userInfo_);
      }
      for (int i = 0; i < friends_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, friends_.get(i));
      }
      for (int i = 0; i < groups_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, groups_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.LoginInitAllInfoSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.LoginInitAllInfoMsg.internal_static_protocol_LoginInitAllInfoSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.LoginInitAllInfoMsg.internal_static_protocol_LoginInitAllInfoSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.class, protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.Builder.class);
      }

      // Construct using protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserInfoFieldBuilder();
          getFriendsFieldBuilder();
          getGroupsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userInfoBuilder_ == null) {
          userInfo_ = protocol.Data.UserData.UserItem.getDefaultInstance();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          friendsBuilder_.clear();
        }
        if (groupsBuilder_ == null) {
          groups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          groupsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.LoginInitAllInfoMsg.internal_static_protocol_LoginInitAllInfoSync_descriptor;
      }

      public protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync getDefaultInstanceForType() {
        return protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.getDefaultInstance();
      }

      public protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync build() {
        protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync buildPartial() {
        protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync result = new protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        if (friendsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            friends_ = java.util.Collections.unmodifiableList(friends_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.friends_ = friends_;
        } else {
          result.friends_ = friendsBuilder_.build();
        }
        if (groupsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            groups_ = java.util.Collections.unmodifiableList(groups_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.groups_ = groups_;
        } else {
          result.groups_ = groupsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync) {
          return mergeFrom((protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync other) {
        if (other == protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync.getDefaultInstance()) return this;
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        if (friendsBuilder_ == null) {
          if (!other.friends_.isEmpty()) {
            if (friends_.isEmpty()) {
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFriendsIsMutable();
              friends_.addAll(other.friends_);
            }
            onChanged();
          }
        } else {
          if (!other.friends_.isEmpty()) {
            if (friendsBuilder_.isEmpty()) {
              friendsBuilder_.dispose();
              friendsBuilder_ = null;
              friends_ = other.friends_;
              bitField0_ = (bitField0_ & ~0x00000002);
              friendsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFriendsFieldBuilder() : null;
            } else {
              friendsBuilder_.addAllMessages(other.friends_);
            }
          }
        }
        if (groupsBuilder_ == null) {
          if (!other.groups_.isEmpty()) {
            if (groups_.isEmpty()) {
              groups_ = other.groups_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGroupsIsMutable();
              groups_.addAll(other.groups_);
            }
            onChanged();
          }
        } else {
          if (!other.groups_.isEmpty()) {
            if (groupsBuilder_.isEmpty()) {
              groupsBuilder_.dispose();
              groupsBuilder_ = null;
              groups_ = other.groups_;
              bitField0_ = (bitField0_ & ~0x00000004);
              groupsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGroupsFieldBuilder() : null;
            } else {
              groupsBuilder_.addAllMessages(other.groups_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserInfo()) {
          
          return false;
        }
        if (!getUserInfo().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getFriendsCount(); i++) {
          if (!getFriends(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getGroupsCount(); i++) {
          if (!getGroups(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.LoginInitAllInfoMsg.LoginInitAllInfoSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.UserItem userInfo = 1;
      private protocol.Data.UserData.UserItem userInfo_ = protocol.Data.UserData.UserItem.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder> userInfoBuilder_;
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public boolean hasUserInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public protocol.Data.UserData.UserItem getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public Builder setUserInfo(protocol.Data.UserData.UserItem value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public Builder setUserInfo(
          protocol.Data.UserData.UserItem.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public Builder mergeUserInfo(protocol.Data.UserData.UserItem value) {
        if (userInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userInfo_ != protocol.Data.UserData.UserItem.getDefaultInstance()) {
            userInfo_ =
              protocol.Data.UserData.UserItem.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = protocol.Data.UserData.UserItem.getDefaultInstance();
          onChanged();
        } else {
          userInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public protocol.Data.UserData.UserItem.Builder getUserInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      public protocol.Data.UserData.UserItemOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_;
        }
      }
      /**
       * <code>required .protocol.UserItem userInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder>(
                  userInfo_,
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }

      // repeated .protocol.UserItem friends = 2;
      private java.util.List<protocol.Data.UserData.UserItem> friends_ =
        java.util.Collections.emptyList();
      private void ensureFriendsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          friends_ = new java.util.ArrayList<protocol.Data.UserData.UserItem>(friends_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder> friendsBuilder_;

      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public java.util.List<protocol.Data.UserData.UserItem> getFriendsList() {
        if (friendsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(friends_);
        } else {
          return friendsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public int getFriendsCount() {
        if (friendsBuilder_ == null) {
          return friends_.size();
        } else {
          return friendsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public protocol.Data.UserData.UserItem getFriends(int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);
        } else {
          return friendsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder setFriends(
          int index, protocol.Data.UserData.UserItem value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.set(index, value);
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder setFriends(
          int index, protocol.Data.UserData.UserItem.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.set(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder addFriends(protocol.Data.UserData.UserItem value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder addFriends(
          int index, protocol.Data.UserData.UserItem value) {
        if (friendsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFriendsIsMutable();
          friends_.add(index, value);
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder addFriends(
          protocol.Data.UserData.UserItem.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder addFriends(
          int index, protocol.Data.UserData.UserItem.Builder builderForValue) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.add(index, builderForValue.build());
          onChanged();
        } else {
          friendsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder addAllFriends(
          java.lang.Iterable<? extends protocol.Data.UserData.UserItem> values) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          super.addAll(values, friends_);
          onChanged();
        } else {
          friendsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder clearFriends() {
        if (friendsBuilder_ == null) {
          friends_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          friendsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public Builder removeFriends(int index) {
        if (friendsBuilder_ == null) {
          ensureFriendsIsMutable();
          friends_.remove(index);
          onChanged();
        } else {
          friendsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public protocol.Data.UserData.UserItem.Builder getFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public protocol.Data.UserData.UserItemOrBuilder getFriendsOrBuilder(
          int index) {
        if (friendsBuilder_ == null) {
          return friends_.get(index);  } else {
          return friendsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public java.util.List<? extends protocol.Data.UserData.UserItemOrBuilder> 
           getFriendsOrBuilderList() {
        if (friendsBuilder_ != null) {
          return friendsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(friends_);
        }
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public protocol.Data.UserData.UserItem.Builder addFriendsBuilder() {
        return getFriendsFieldBuilder().addBuilder(
            protocol.Data.UserData.UserItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public protocol.Data.UserData.UserItem.Builder addFriendsBuilder(
          int index) {
        return getFriendsFieldBuilder().addBuilder(
            index, protocol.Data.UserData.UserItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.UserItem friends = 2;</code>
       */
      public java.util.List<protocol.Data.UserData.UserItem.Builder> 
           getFriendsBuilderList() {
        return getFriendsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder> 
          getFriendsFieldBuilder() {
        if (friendsBuilder_ == null) {
          friendsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol.Data.UserData.UserItem, protocol.Data.UserData.UserItem.Builder, protocol.Data.UserData.UserItemOrBuilder>(
                  friends_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          friends_ = null;
        }
        return friendsBuilder_;
      }

      // repeated .protocol.GroupItem groups = 3;
      private java.util.List<protocol.Data.GroupData.GroupItem> groups_ =
        java.util.Collections.emptyList();
      private void ensureGroupsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          groups_ = new java.util.ArrayList<protocol.Data.GroupData.GroupItem>(groups_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.Data.GroupData.GroupItem, protocol.Data.GroupData.GroupItem.Builder, protocol.Data.GroupData.GroupItemOrBuilder> groupsBuilder_;

      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public java.util.List<protocol.Data.GroupData.GroupItem> getGroupsList() {
        if (groupsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(groups_);
        } else {
          return groupsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public int getGroupsCount() {
        if (groupsBuilder_ == null) {
          return groups_.size();
        } else {
          return groupsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public protocol.Data.GroupData.GroupItem getGroups(int index) {
        if (groupsBuilder_ == null) {
          return groups_.get(index);
        } else {
          return groupsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder setGroups(
          int index, protocol.Data.GroupData.GroupItem value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.set(index, value);
          onChanged();
        } else {
          groupsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder setGroups(
          int index, protocol.Data.GroupData.GroupItem.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.set(index, builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder addGroups(protocol.Data.GroupData.GroupItem value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.add(value);
          onChanged();
        } else {
          groupsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder addGroups(
          int index, protocol.Data.GroupData.GroupItem value) {
        if (groupsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGroupsIsMutable();
          groups_.add(index, value);
          onChanged();
        } else {
          groupsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder addGroups(
          protocol.Data.GroupData.GroupItem.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.add(builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder addGroups(
          int index, protocol.Data.GroupData.GroupItem.Builder builderForValue) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.add(index, builderForValue.build());
          onChanged();
        } else {
          groupsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder addAllGroups(
          java.lang.Iterable<? extends protocol.Data.GroupData.GroupItem> values) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          super.addAll(values, groups_);
          onChanged();
        } else {
          groupsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder clearGroups() {
        if (groupsBuilder_ == null) {
          groups_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          groupsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public Builder removeGroups(int index) {
        if (groupsBuilder_ == null) {
          ensureGroupsIsMutable();
          groups_.remove(index);
          onChanged();
        } else {
          groupsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public protocol.Data.GroupData.GroupItem.Builder getGroupsBuilder(
          int index) {
        return getGroupsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public protocol.Data.GroupData.GroupItemOrBuilder getGroupsOrBuilder(
          int index) {
        if (groupsBuilder_ == null) {
          return groups_.get(index);  } else {
          return groupsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public java.util.List<? extends protocol.Data.GroupData.GroupItemOrBuilder> 
           getGroupsOrBuilderList() {
        if (groupsBuilder_ != null) {
          return groupsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(groups_);
        }
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public protocol.Data.GroupData.GroupItem.Builder addGroupsBuilder() {
        return getGroupsFieldBuilder().addBuilder(
            protocol.Data.GroupData.GroupItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public protocol.Data.GroupData.GroupItem.Builder addGroupsBuilder(
          int index) {
        return getGroupsFieldBuilder().addBuilder(
            index, protocol.Data.GroupData.GroupItem.getDefaultInstance());
      }
      /**
       * <code>repeated .protocol.GroupItem groups = 3;</code>
       */
      public java.util.List<protocol.Data.GroupData.GroupItem.Builder> 
           getGroupsBuilderList() {
        return getGroupsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protocol.Data.GroupData.GroupItem, protocol.Data.GroupData.GroupItem.Builder, protocol.Data.GroupData.GroupItemOrBuilder> 
          getGroupsFieldBuilder() {
        if (groupsBuilder_ == null) {
          groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protocol.Data.GroupData.GroupItem, protocol.Data.GroupData.GroupItem.Builder, protocol.Data.GroupData.GroupItemOrBuilder>(
                  groups_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          groups_ = null;
        }
        return groupsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protocol.LoginInitAllInfoSync)
    }

    static {
      defaultInstance = new LoginInitAllInfoSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.LoginInitAllInfoSync)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_LoginInitAllInfoSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_LoginInitAllInfoSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031LoginInitAllInfoMsg.proto\022\010protocol\032\016U" +
      "serData.proto\032\017GroupData.proto\"\206\001\n\024Login" +
      "InitAllInfoSync\022$\n\010userInfo\030\001 \002(\0132\022.prot" +
      "ocol.UserItem\022#\n\007friends\030\002 \003(\0132\022.protoco" +
      "l.UserItem\022#\n\006groups\030\003 \003(\0132\023.protocol.Gr" +
      "oupItemB\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_LoginInitAllInfoSync_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_LoginInitAllInfoSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_LoginInitAllInfoSync_descriptor,
              new java.lang.String[] { "UserInfo", "Friends", "Groups", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Data.UserData.getDescriptor(),
          protocol.Data.GroupData.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
