// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OffLineMsg.proto

package protocol.Msg;

public final class OffLineMsg {
  private OffLineMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OffLineSyncOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.OffLineSync.CauseCode causeCode = 1;
    /**
     * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
     */
    boolean hasCauseCode();
    /**
     * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
     */
    protocol.Msg.OffLineMsg.OffLineSync.CauseCode getCauseCode();
  }
  /**
   * Protobuf type {@code protocol.OffLineSync}
   */
  public static final class OffLineSync extends
      com.google.protobuf.GeneratedMessage
      implements OffLineSyncOrBuilder {
    // Use OffLineSync.newBuilder() to construct.
    private OffLineSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OffLineSync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OffLineSync defaultInstance;
    public static OffLineSync getDefaultInstance() {
      return defaultInstance;
    }

    public OffLineSync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OffLineSync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.OffLineMsg.OffLineSync.CauseCode value = protocol.Msg.OffLineMsg.OffLineSync.CauseCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                causeCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.OffLineMsg.internal_static_protocol_OffLineSync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.OffLineMsg.internal_static_protocol_OffLineSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.OffLineMsg.OffLineSync.class, protocol.Msg.OffLineMsg.OffLineSync.Builder.class);
    }

    public static com.google.protobuf.Parser<OffLineSync> PARSER =
        new com.google.protobuf.AbstractParser<OffLineSync>() {
      public OffLineSync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OffLineSync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OffLineSync> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.OffLineSync.CauseCode}
     *
     * <pre>
     *下线原因
     * </pre>
     */
    public enum CauseCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CHANGE_PASSWORD = 0;</code>
       *
       * <pre>
       *修改密码
       * </pre>
       */
      CHANGE_PASSWORD(0, 0),
      /**
       * <code>ANOTHER_LOGIN = 1;</code>
       *
       * <pre>
       *其他设备登录
       * </pre>
       */
      ANOTHER_LOGIN(1, 1),
      /**
       * <code>KEEP_ALIVE_FALSE = 2;</code>
       */
      KEEP_ALIVE_FALSE(2, 2),
      ;

      /**
       * <code>CHANGE_PASSWORD = 0;</code>
       *
       * <pre>
       *修改密码
       * </pre>
       */
      public static final int CHANGE_PASSWORD_VALUE = 0;
      /**
       * <code>ANOTHER_LOGIN = 1;</code>
       *
       * <pre>
       *其他设备登录
       * </pre>
       */
      public static final int ANOTHER_LOGIN_VALUE = 1;
      /**
       * <code>KEEP_ALIVE_FALSE = 2;</code>
       */
      public static final int KEEP_ALIVE_FALSE_VALUE = 2;


      public final int getNumber() { return value; }

      public static CauseCode valueOf(int value) {
        switch (value) {
          case 0: return CHANGE_PASSWORD;
          case 1: return ANOTHER_LOGIN;
          case 2: return KEEP_ALIVE_FALSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CauseCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<CauseCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CauseCode>() {
              public CauseCode findValueByNumber(int number) {
                return CauseCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.OffLineMsg.OffLineSync.getDescriptor().getEnumTypes().get(0);
      }

      private static final CauseCode[] VALUES = values();

      public static CauseCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private CauseCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.OffLineSync.CauseCode)
    }

    private int bitField0_;
    // required .protocol.OffLineSync.CauseCode causeCode = 1;
    public static final int CAUSECODE_FIELD_NUMBER = 1;
    private protocol.Msg.OffLineMsg.OffLineSync.CauseCode causeCode_;
    /**
     * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
     */
    public boolean hasCauseCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
     */
    public protocol.Msg.OffLineMsg.OffLineSync.CauseCode getCauseCode() {
      return causeCode_;
    }

    private void initFields() {
      causeCode_ = protocol.Msg.OffLineMsg.OffLineSync.CauseCode.CHANGE_PASSWORD;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCauseCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, causeCode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, causeCode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.OffLineMsg.OffLineSync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.OffLineMsg.OffLineSync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.OffLineSync}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.OffLineMsg.OffLineSyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.OffLineMsg.internal_static_protocol_OffLineSync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.OffLineMsg.internal_static_protocol_OffLineSync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.OffLineMsg.OffLineSync.class, protocol.Msg.OffLineMsg.OffLineSync.Builder.class);
      }

      // Construct using protocol.Msg.OffLineMsg.OffLineSync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        causeCode_ = protocol.Msg.OffLineMsg.OffLineSync.CauseCode.CHANGE_PASSWORD;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.OffLineMsg.internal_static_protocol_OffLineSync_descriptor;
      }

      public protocol.Msg.OffLineMsg.OffLineSync getDefaultInstanceForType() {
        return protocol.Msg.OffLineMsg.OffLineSync.getDefaultInstance();
      }

      public protocol.Msg.OffLineMsg.OffLineSync build() {
        protocol.Msg.OffLineMsg.OffLineSync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.OffLineMsg.OffLineSync buildPartial() {
        protocol.Msg.OffLineMsg.OffLineSync result = new protocol.Msg.OffLineMsg.OffLineSync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.causeCode_ = causeCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.OffLineMsg.OffLineSync) {
          return mergeFrom((protocol.Msg.OffLineMsg.OffLineSync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.OffLineMsg.OffLineSync other) {
        if (other == protocol.Msg.OffLineMsg.OffLineSync.getDefaultInstance()) return this;
        if (other.hasCauseCode()) {
          setCauseCode(other.getCauseCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCauseCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.OffLineMsg.OffLineSync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.OffLineMsg.OffLineSync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.OffLineSync.CauseCode causeCode = 1;
      private protocol.Msg.OffLineMsg.OffLineSync.CauseCode causeCode_ = protocol.Msg.OffLineMsg.OffLineSync.CauseCode.CHANGE_PASSWORD;
      /**
       * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
       */
      public boolean hasCauseCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
       */
      public protocol.Msg.OffLineMsg.OffLineSync.CauseCode getCauseCode() {
        return causeCode_;
      }
      /**
       * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
       */
      public Builder setCauseCode(protocol.Msg.OffLineMsg.OffLineSync.CauseCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        causeCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.OffLineSync.CauseCode causeCode = 1;</code>
       */
      public Builder clearCauseCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        causeCode_ = protocol.Msg.OffLineMsg.OffLineSync.CauseCode.CHANGE_PASSWORD;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.OffLineSync)
    }

    static {
      defaultInstance = new OffLineSync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.OffLineSync)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_OffLineSync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_OffLineSync_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020OffLineMsg.proto\022\010protocol\"\214\001\n\013OffLine" +
      "Sync\0222\n\tcauseCode\030\001 \002(\0162\037.protocol.OffLi" +
      "neSync.CauseCode\"I\n\tCauseCode\022\023\n\017CHANGE_" +
      "PASSWORD\020\000\022\021\n\rANOTHER_LOGIN\020\001\022\024\n\020KEEP_AL" +
      "IVE_FALSE\020\002B\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_OffLineSync_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_OffLineSync_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_OffLineSync_descriptor,
              new java.lang.String[] { "CauseCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
