// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SendGroupChatMsg.proto

package protocol.Msg;

public final class SendGroupChatMsg {
  private SendGroupChatMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SendGroupChatReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.ChatItem chatData = 1;
    /**
     * <code>required .protocol.ChatItem chatData = 1;</code>
     */
    boolean hasChatData();
    /**
     * <code>required .protocol.ChatItem chatData = 1;</code>
     */
    protocol.Data.ChatData.ChatItem getChatData();
    /**
     * <code>required .protocol.ChatItem chatData = 1;</code>
     */
    protocol.Data.ChatData.ChatItemOrBuilder getChatDataOrBuilder();

    // required int32 groupId = 2;
    /**
     * <code>required int32 groupId = 2;</code>
     */
    boolean hasGroupId();
    /**
     * <code>required int32 groupId = 2;</code>
     */
    int getGroupId();
  }
  /**
   * Protobuf type {@code protocol.SendGroupChatReq}
   */
  public static final class SendGroupChatReq extends
      com.google.protobuf.GeneratedMessage
      implements SendGroupChatReqOrBuilder {
    // Use SendGroupChatReq.newBuilder() to construct.
    private SendGroupChatReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendGroupChatReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendGroupChatReq defaultInstance;
    public static SendGroupChatReq getDefaultInstance() {
      return defaultInstance;
    }

    public SendGroupChatReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendGroupChatReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.Data.ChatData.ChatItem.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = chatData_.toBuilder();
              }
              chatData_ = input.readMessage(protocol.Data.ChatData.ChatItem.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chatData_);
                chatData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              groupId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.SendGroupChatMsg.SendGroupChatReq.class, protocol.Msg.SendGroupChatMsg.SendGroupChatReq.Builder.class);
    }

    public static com.google.protobuf.Parser<SendGroupChatReq> PARSER =
        new com.google.protobuf.AbstractParser<SendGroupChatReq>() {
      public SendGroupChatReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendGroupChatReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendGroupChatReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .protocol.ChatItem chatData = 1;
    public static final int CHATDATA_FIELD_NUMBER = 1;
    private protocol.Data.ChatData.ChatItem chatData_;
    /**
     * <code>required .protocol.ChatItem chatData = 1;</code>
     */
    public boolean hasChatData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.ChatItem chatData = 1;</code>
     */
    public protocol.Data.ChatData.ChatItem getChatData() {
      return chatData_;
    }
    /**
     * <code>required .protocol.ChatItem chatData = 1;</code>
     */
    public protocol.Data.ChatData.ChatItemOrBuilder getChatDataOrBuilder() {
      return chatData_;
    }

    // required int32 groupId = 2;
    public static final int GROUPID_FIELD_NUMBER = 2;
    private int groupId_;
    /**
     * <code>required int32 groupId = 2;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 groupId = 2;</code>
     */
    public int getGroupId() {
      return groupId_;
    }

    private void initFields() {
      chatData_ = protocol.Data.ChatData.ChatItem.getDefaultInstance();
      groupId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasChatData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGroupId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getChatData().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, chatData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, groupId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, chatData_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, groupId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.SendGroupChatMsg.SendGroupChatReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.SendGroupChatReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.SendGroupChatMsg.SendGroupChatReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.SendGroupChatMsg.SendGroupChatReq.class, protocol.Msg.SendGroupChatMsg.SendGroupChatReq.Builder.class);
      }

      // Construct using protocol.Msg.SendGroupChatMsg.SendGroupChatReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getChatDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (chatDataBuilder_ == null) {
          chatData_ = protocol.Data.ChatData.ChatItem.getDefaultInstance();
        } else {
          chatDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        groupId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatReq_descriptor;
      }

      public protocol.Msg.SendGroupChatMsg.SendGroupChatReq getDefaultInstanceForType() {
        return protocol.Msg.SendGroupChatMsg.SendGroupChatReq.getDefaultInstance();
      }

      public protocol.Msg.SendGroupChatMsg.SendGroupChatReq build() {
        protocol.Msg.SendGroupChatMsg.SendGroupChatReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.SendGroupChatMsg.SendGroupChatReq buildPartial() {
        protocol.Msg.SendGroupChatMsg.SendGroupChatReq result = new protocol.Msg.SendGroupChatMsg.SendGroupChatReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (chatDataBuilder_ == null) {
          result.chatData_ = chatData_;
        } else {
          result.chatData_ = chatDataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.groupId_ = groupId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.SendGroupChatMsg.SendGroupChatReq) {
          return mergeFrom((protocol.Msg.SendGroupChatMsg.SendGroupChatReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.SendGroupChatMsg.SendGroupChatReq other) {
        if (other == protocol.Msg.SendGroupChatMsg.SendGroupChatReq.getDefaultInstance()) return this;
        if (other.hasChatData()) {
          mergeChatData(other.getChatData());
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasChatData()) {
          
          return false;
        }
        if (!hasGroupId()) {
          
          return false;
        }
        if (!getChatData().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.SendGroupChatMsg.SendGroupChatReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.SendGroupChatMsg.SendGroupChatReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.ChatItem chatData = 1;
      private protocol.Data.ChatData.ChatItem chatData_ = protocol.Data.ChatData.ChatItem.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.ChatData.ChatItem, protocol.Data.ChatData.ChatItem.Builder, protocol.Data.ChatData.ChatItemOrBuilder> chatDataBuilder_;
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public boolean hasChatData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public protocol.Data.ChatData.ChatItem getChatData() {
        if (chatDataBuilder_ == null) {
          return chatData_;
        } else {
          return chatDataBuilder_.getMessage();
        }
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public Builder setChatData(protocol.Data.ChatData.ChatItem value) {
        if (chatDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chatData_ = value;
          onChanged();
        } else {
          chatDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public Builder setChatData(
          protocol.Data.ChatData.ChatItem.Builder builderForValue) {
        if (chatDataBuilder_ == null) {
          chatData_ = builderForValue.build();
          onChanged();
        } else {
          chatDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public Builder mergeChatData(protocol.Data.ChatData.ChatItem value) {
        if (chatDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              chatData_ != protocol.Data.ChatData.ChatItem.getDefaultInstance()) {
            chatData_ =
              protocol.Data.ChatData.ChatItem.newBuilder(chatData_).mergeFrom(value).buildPartial();
          } else {
            chatData_ = value;
          }
          onChanged();
        } else {
          chatDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public Builder clearChatData() {
        if (chatDataBuilder_ == null) {
          chatData_ = protocol.Data.ChatData.ChatItem.getDefaultInstance();
          onChanged();
        } else {
          chatDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public protocol.Data.ChatData.ChatItem.Builder getChatDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getChatDataFieldBuilder().getBuilder();
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      public protocol.Data.ChatData.ChatItemOrBuilder getChatDataOrBuilder() {
        if (chatDataBuilder_ != null) {
          return chatDataBuilder_.getMessageOrBuilder();
        } else {
          return chatData_;
        }
      }
      /**
       * <code>required .protocol.ChatItem chatData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protocol.Data.ChatData.ChatItem, protocol.Data.ChatData.ChatItem.Builder, protocol.Data.ChatData.ChatItemOrBuilder> 
          getChatDataFieldBuilder() {
        if (chatDataBuilder_ == null) {
          chatDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protocol.Data.ChatData.ChatItem, protocol.Data.ChatData.ChatItem.Builder, protocol.Data.ChatData.ChatItemOrBuilder>(
                  chatData_,
                  getParentForChildren(),
                  isClean());
          chatData_ = null;
        }
        return chatDataBuilder_;
      }

      // required int32 groupId = 2;
      private int groupId_ ;
      /**
       * <code>required int32 groupId = 2;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 groupId = 2;</code>
       */
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>required int32 groupId = 2;</code>
       */
      public Builder setGroupId(int value) {
        bitField0_ |= 0x00000002;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 groupId = 2;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        groupId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.SendGroupChatReq)
    }

    static {
      defaultInstance = new SendGroupChatReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.SendGroupChatReq)
  }

  public interface SendGroupChatRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;
    /**
     * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode getResultCode();
  }
  /**
   * Protobuf type {@code protocol.SendGroupChatRsp}
   */
  public static final class SendGroupChatRsp extends
      com.google.protobuf.GeneratedMessage
      implements SendGroupChatRspOrBuilder {
    // Use SendGroupChatRsp.newBuilder() to construct.
    private SendGroupChatRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SendGroupChatRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SendGroupChatRsp defaultInstance;
    public static SendGroupChatRsp getDefaultInstance() {
      return defaultInstance;
    }

    public SendGroupChatRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SendGroupChatRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode value = protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                resultCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.class, protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<SendGroupChatRsp> PARSER =
        new com.google.protobuf.AbstractParser<SendGroupChatRsp>() {
      public SendGroupChatRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendGroupChatRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SendGroupChatRsp> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code protocol.SendGroupChatRsp.ResultCode}
     */
    public enum ResultCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>FAIL = 1;</code>
       */
      FAIL(1, 1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>FAIL = 1;</code>
       */
      public static final int FAIL_VALUE = 1;


      public final int getNumber() { return value; }

      public static ResultCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ResultCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResultCode>() {
              public ResultCode findValueByNumber(int number) {
                return ResultCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResultCode[] VALUES = values();

      public static ResultCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ResultCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protocol.SendGroupChatRsp.ResultCode)
    }

    private int bitField0_;
    // required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode resultCode_;
    /**
     * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
     */
    public protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode getResultCode() {
      return resultCode_;
    }

    private void initFields() {
      resultCode_ = protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResultCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, resultCode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, resultCode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.Msg.SendGroupChatMsg.SendGroupChatRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.SendGroupChatRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protocol.Msg.SendGroupChatMsg.SendGroupChatRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.class, protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.Builder.class);
      }

      // Construct using protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resultCode_ = protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.Msg.SendGroupChatMsg.internal_static_protocol_SendGroupChatRsp_descriptor;
      }

      public protocol.Msg.SendGroupChatMsg.SendGroupChatRsp getDefaultInstanceForType() {
        return protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.getDefaultInstance();
      }

      public protocol.Msg.SendGroupChatMsg.SendGroupChatRsp build() {
        protocol.Msg.SendGroupChatMsg.SendGroupChatRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.Msg.SendGroupChatMsg.SendGroupChatRsp buildPartial() {
        protocol.Msg.SendGroupChatMsg.SendGroupChatRsp result = new protocol.Msg.SendGroupChatMsg.SendGroupChatRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.Msg.SendGroupChatMsg.SendGroupChatRsp) {
          return mergeFrom((protocol.Msg.SendGroupChatMsg.SendGroupChatRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.Msg.SendGroupChatMsg.SendGroupChatRsp other) {
        if (other == protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResultCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.Msg.SendGroupChatMsg.SendGroupChatRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.Msg.SendGroupChatMsg.SendGroupChatRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;
      private protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode resultCode_ = protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode.SUCCESS;
      /**
       * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode getResultCode() {
        return resultCode_;
      }
      /**
       * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public Builder setResultCode(protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .protocol.SendGroupChatRsp.ResultCode resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = protocol.Msg.SendGroupChatMsg.SendGroupChatRsp.ResultCode.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:protocol.SendGroupChatRsp)
    }

    static {
      defaultInstance = new SendGroupChatRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protocol.SendGroupChatRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SendGroupChatReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_SendGroupChatReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_SendGroupChatRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protocol_SendGroupChatRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026SendGroupChatMsg.proto\022\010protocol\032\016Chat" +
      "Data.proto\"I\n\020SendGroupChatReq\022$\n\010chatDa" +
      "ta\030\001 \002(\0132\022.protocol.ChatItem\022\017\n\007groupId\030" +
      "\002 \002(\005\"r\n\020SendGroupChatRsp\0229\n\nresultCode\030" +
      "\001 \002(\0162%.protocol.SendGroupChatRsp.Result" +
      "Code\"#\n\nResultCode\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL\020" +
      "\001B\016\n\014protocol.Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protocol_SendGroupChatReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protocol_SendGroupChatReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_SendGroupChatReq_descriptor,
              new java.lang.String[] { "ChatData", "GroupId", });
          internal_static_protocol_SendGroupChatRsp_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_protocol_SendGroupChatRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protocol_SendGroupChatRsp_descriptor,
              new java.lang.String[] { "ResultCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Data.ChatData.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
